sudo: required
services:
  - docker
env:
  global:
    #Get the current commit version to be used in the deployment for tagging and updating
    - SHA = $(git rev-parse HEAD)
    #disable prompts throughout the deployment process
    - CLOUDSDK_CORE_DISABLE_PROMPTS = 1
before_install:
  #insert command invoking the travis-encrypted access to gcp
  -  openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  #download gcp sdk cli and install it in such directory
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  #source sdk file to modify the shell commands
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl 
  - gcloud auth activate-service-account --key-file service-account.json
  #next gcloud commands need to be run in the gcloud shell as well!!!
  - gcloud config set project k8s-production-deployment
  - gcloud config set compute/zone us-central1-c 
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t eddierock55/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eddierock55/react-test npm test

deploy: 
  #for a k8s deployment, another script is necessary, here we are sourcing it
  provider: script 
  script: bash ./deploy.sh
  on:
    branch: master